export {default as Hero} from './Hero/Hero'
export {default as FeaturedWrapper} from './FeaturedWrapper/FeaturedWrapper'
export {default as FeaturedCollection} from './FeaturedCollection/FeaturedCollection'
export {default as FeaturedCategories} from './FeaturedCategories/FeaturedCategories'
export {default as FeaturedCategoriesList} from './FeaturedCategories/FeaturedCategoriesList/FeaturedCategoriesList'
