export {default as Home} from './Home/Home'
export {default as Shop} from './Shop/Shop'
export {default as ProductCategory} from './ProductCategory/ProductCategory'
export {default as Contact} from './Contact/Contact'
export {default as Cart} from './Cart/Cart'
export {default as Checkout} from './Checkout/Checkout'
export {default as NoPage} from './NoPage/NoPage'
export {default as ProductDetailsPage} from './ProductDetailsPage/ProductDetailsPage'
