export {default as Home} from './Home/Home'
export {default as Blog} from './Blog/Blog'
export {default as FoodList} from './FoodList/FoodList'
export {default as Contact} from './Contact/Contact'
export {default as Login} from './Login/Login'
export {default as Cart} from './Cart/Cart'
export {default as NoPage} from './NoPage/NoPage'
export {default as ItemDetails} from './ItemDetails/ItemDetails'
